### ISSUE TITLE
SSRG553 - StalinLocker Detector. - Currently very noisy 

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#10]
SSRG553 - StalinLocker Detector. - Currently very noisy 

Working on additional filtering options

**Comment by jward51** [comment]
No changes noticed about the query since first reported

**Comment by jward51** [comment]
This correlation search query still need a lot of work to tune out a tremendous amount of noise.

**Comment by jward51** [comment]
process_name = "miiserver.exe" ---> 



Proposed new query :

`windows` ((source="WinEventLog:Microsoft-Windows-Sysmon/Operational" OR source="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational") (((EventCode="13" (TargetObject="HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\Stalin" OR TargetObject="HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\Stalin")) OR (EventCode="1" (Image="*\\fl.dat" OR Image="*\\stalin.exe" OR Image="*\\USSR_Anthem.mp3"))) OR (EventCode="1" (file_hash="853177d9a42fab0d8d62a190894de5c27ec203240df0d9e70154a675823adf04")) OR EventCode="11"))
(NOT process_exec="MsMpEng.exe" NOT process_exe="AgentMon.exe" NOT process_name="MsSense*.exe" NOT process_name="ALsvc.exe" NOT process_name="miiserver.exe" NOT TargetFileName="*\\Windows\\SoftwareDistribution\\Download\\Install\\*" NOT TargetFilename="*\\Microsoft\\Windows\\UpdateOrchestrator*" NOT TargetFilename="*\\Windows\\SoftwareDistribution\\Download\\Install\\*" NOT TargetFilename="*\\Sophos\\Sophos*")
| table TargetFilename,EventCode,Image,TargetObject,ParentImage,Hashes | `patronus_helper`

**Comment by jward51** [comment]
process_exec = "MsMpEng.exe" --> Microsoft\Windows Defender\Definition Updates
process_name = MsSense.exe ---> Windows Defender Advanced Threat Protection
miiserver.exe ---> Microsoft Azure AD Sync
ALsvc.exe ---> Sophos\AutoUpdate\Cache

I've updated the query in patronus-dev instance  : 


(NOT process_exec="MsMpEng.exe" NOT process_name="MsSense.exe" NOT process_name="ALsvc.exe" NOT process_name="miiserver.exe" NOT TargetFileName="\Windows\SoftwareDistribution\Download\Install\" NOT TargetFilename="\Microsoft\Windows\UpdateOrchestrator" NOT TargetFilename="\Windows\SoftwareDistribution\Download\Install\" NOT TargetFilename="\Sophos\Sophos")

**Comment by jward51** [comment]
Updated the SSRG553 - StalinLocker Detector query to include more filtering

**Comment by cmutt78** [comment]
@jward51 where was this updated?
