### ISSUE TITLE
SSRG014 - Host With Multiple Infections

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#24]
What is the purpose for the pipe  "| search Malware_Attacks.category=av.detect"

| tstats summariesonly=true allow_old_summaries=true dc(Malware_Attacks.signature) as "infection_count" from datamodel=Malware.Malware_Attacks by "Malware_Attacks.dest" "Malware_Attacks.category" 
| search Malware_Attacks.category=av.detect
| rename "Malware_Attacks.dest" as "dest"
| where 'infection_count'>1
| `patronus_helper`

**Comment by cmutt78** [comment]
needs to be removed.  was a specific use case when first developed
