### ISSUE TITLE
SSRG015 - New User Account Created On Multiple Hosts

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#25]
Missing useraccounts_tracker lookup.  Should this be coming from one of the Patronus required apps?

| from inputlookup:"useraccounts_tracker" 
| eval earliestQual=case(match("-24h@h", "^\d"), tostring("-24h@h"), match("-24h@h", "^([@\+-]){1}"), relative_time(time(), "-24h@h"), true(), time()) 
| eval latestQual=case(match("+0s", "^\d"), tostring("+0s"), match("+0s", "^([@\+-]){1}"), relative_time(time(), "+0s"), true(), time()) 
| where ('firstTime'>=earliestQual AND 'firstTime'<=latestQual) 
| fields - earliestQual, latestQual 
| stats dc(dest) as "dest_count" by "user" 
| where 'dest_count'>3
| `patronus_helper`

**Comment by cmutt78** [comment]
removing from the app
