### ISSUE TITLE
SSRG023 - New Logon Type for User

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#26]
Suggest updated query with filtering : 

`windows_security` Logon_Type=* Logon Type TaskCategory=Logon Audit Success (NOT user=*$ NOT user = SYSTEM NOT user="LOCAL SERVICE" NOT user="NETWORK SERVICE")
| table _time user Logon_Type  
| `patronus_helper`

**Comment by cmutt78** [comment]
going to leave query as-is.  those can be filters if noise is too much
