### ISSUE TITLE
`sysmon` macro 

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#36]
The sysmon macro shows :

index = main source="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational"

Suggested change : 

index=wineventlog  OR index = main source="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" OR source="WinEventLog:Microsoft-Windows-Sysmon/Operational"

**Comment by cmutt78** [comment]
This macro is a placeholder.  Meant for users to update while implementing.
