### ISSUE TITLE
SSRG030 - First Time Seen Running Windows Service

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#40]
ERROR SavedSplunker - savedsearch_id="nobody;patronus;SSRG030 - First Time Seen Running Windows Service", message="Error in 'lookup' command: Could not construct lookup 'ssrg_tracker_first_seen_windows_service.csv, key, OUTPUT, firstSeen'. See search.log for more details.". No actions executed

**Comment by cmutt78** [comment]
This is not an issue but needs to be primed before first use.  Run the search over 7 days manually and remove the append=t to build out the lookup with base values
