### ISSUE TITLE
Asset Tracker - Lookup Gen

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#41]
Suggested updated query : 

index=_internal NOT host = *splunkcloud* |stats max(_time) as lastSeen by host
|inputlookup append=true ss_asset_tracker
|dedup host sortby - lastSeen
| eval host = lower(host)
|table host lastSeen
|outputlookup ss_asset_tracker

**Comment by cmutt78** [comment]
added the exclusion for cloud systems but leaving host intact
