### ISSUE TITLE
Asset Page Unmanaged Assets

### ISSUE THREAD

**Issue by TomDiTullio** [spicosolutions/thepeoplessiem#44]
Unmanaged assets counter on assets page does not track correctly

**Comment by cmutt78** [comment]
need more details

**Comment by cmutt78** [comment]
Changed number only query for unmanaged assets to
`|inputlookup ss_asset_tracker 
|eval key=host
|join type=outer key [|inputlookup ss_asset |mvexpand key |eval found=1]
|where isnull(found)`

to match that of executive overview and detailed view
