### ISSUE TITLE
SSRG041 - Detect User Account Lockout

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#45]
Can we add in EventCode = 4625 to include failed login attempts in the Deep Dive (drilldown) by the selected user?  That way you would be able to see a list of Computers that causing the user to become locked out.  This saves the IT team time trying to track down the info using ad-hoc searches outside of Patronus.

index=wineventlog* source=WinEventLog:Security (EventCode=4740 OR EventCode=4625) NOT user="-" NOT user="*$*"
| stats values(Computer) as Computer values(signature) as signature count min(_time) as firstTime max(_time) as lastTime by user 
| convert ctime(lastTime)

**Comment by cmutt78** [comment]
instead of modifying existing search, create a new search that will generate risk on failed logins 4625
