### ISSUE TITLE
Review Threat Lists

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#47]
I've been alerted of the following src_ip's : 

Unusual Network Scanning | **89.248.165.90** -> 70.42.176.39
https://www.abuseipdb.com/check/89.248.165.90

Unusual Network Scanning | **91.210.107.42** -> 72.5.100.98
https://www.abuseipdb.com/check/91.210.107.42

Unusual Network Scanning | **89.248.165.63** -> 70.42.176.39
https://www.abuseipdb.com/check/89.248.165.63

I don't see these in the current threat list we have configured in <COMPANY REDACTED> Patronus.

**Comment by cmutt78** [comment]
Unusual Network Scanning is not threat driven.  What makes you think they should be in a threat list? @jward51

**Comment by cmutt78** [comment]
not an issue
