### ISSUE TITLE
Timepicker for the Threat Dashboard won't allow you to change the search window

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#48]
Timepicker for the Threat Dashboard won't allow you to change the search window.  It's stuck on Last 24 Hours, if you hit Edit on the dashboard and try to change the time window nothing happens.  BP asked if they could narrow there window to last 60 mins or last 4 hours.

**Comment by cmutt78** [comment]
looked at this and cannot replicate.  @jward51, hit me up to review live

**Comment by cmutt78** [comment]
bug located in searches explicitly set for -24h
