### ISSUE TITLE
The Risk Scoreboard Dashboard has a drilldown to URL that shows "SplunkEnterpriseSecuritySuite"

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#5]
The Risk Scoreboard Dashboard has a drilldown to URL that shows "SplunkEnterpriseSecuritySuite"

The panel I found this on was Asset Details > Identity Details

On Click : Link to custom URL
URL : /app/SplunkEnterpriseSecuritySuite/identity_center?form.username=$row.email$

**Comment by cmutt78** [comment]
scoreboard.xml:496 - no drilldown should exist from here

**Comment by jward51** [comment]
Confirmed that it appears that drilldown is now disabled in the patronus-dev instance
