### ISSUE TITLE
SSRG658 - Rare Service Installs

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#55]
This correlation rule query shows like this currently : 

``windows`  (source="WinEventLog:System" EventCode="7045")
| eventstats dc(ServiceFileName) as val | search val < 5 | `patronus_helper``

However, in Patronus when looking at the events within the Risk Scoreboard I see an empty value on field "user".  This is because the WinEventLog:System events don't have the field user.  The user identifying field is called AccountName.  I suggest added a `| rename AccountName as user` to fill in the missing values.  In my case, this only helped fill in those events that had a AccountName value but a lot of the events have a null value.  

Here's just an idea to change the query so that we achieve capturing the AccountName values to field name user and mark null user events as "unknown"

```
`windows` (source="WinEventLog:System" EventCode="7045") 
| eval user=if(isnull(AccountName),"unknown",AccountName) 
| table user
| eventstats dc(ServiceFileName) as val | search val < 5 | `patronus_helper`
```

**Comment by jward51** [comment]
I also recommend adding tuning to the base search like this : 

NOT (ImagePath="*Splunk*" OR ImagePath=*Sophos* OR ImagePath="*Windows Defender*" OR ImagePath="*C:\\Program Files\\Microsoft Policy Platform\\policyHost.exe*" OR ImagePath="*\\Microsoft Intune Management Extension\\Microsoft.Management.Services.IntuneWindowsAgent.exe*" OR ServiceName="Dell Client Management Service"  OR ServiceName="*Kaseya*" OR ServiceName="*Hitman*" OR ServiceName="*Cisco AnyConnect*" OR ServiceName=*Citrix*)

**Comment by jward51** [comment]
Would it make more sense to have the Risk Message include the "service_name" instead of by user?

**Comment by cmutt78** [comment]
Search changed to below:

`windows` (source="WinEventLog:System" EventCode="7045") 
| eval user=coalesce(AccountName,"unknown") 
| eventstats dc(ServiceFileName) as val 
| search val < 5 
| `patronus_helper`

Filters will be at discretion of customer
