### ISSUE TITLE
SSRG480 - Sysmon state and configuration changed.

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#57]
![image](https://user-images.githubusercontent.com/34247955/190437741-94b5f780-94ab-4cb3-876f-ebea364cb122.png)

This search looks for if the the field "State" or "status" has changed but the risk message still shows a generic format by user which is not captured in the _raw log.  I recommend we show either State or status and value in the [ ] brackets.  For example, the values will be Started or Stopped

**Comment by cmutt78** [comment]
Updated to Detected sysmon state and configuration change on [$result.Computer$] for status [$result.status$] or state [$result.state$]
