### ISSUE TITLE
Filter Management now shows the following pop up alert for SPL safeguards

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#6]
Filter Management now shows the following pop up alert when trying to add new filters.

![filtermgmtalert](https://user-images.githubusercontent.com/34247955/147981104-b7c6c209-b21b-4f6b-a83a-880043a5077a.PNG)

Documentation : 

https://docs.splunk.com/Documentation/SplunkCloud/latest/Security/SPLsafeguards

Created Splunk Cloud ticket to request  'disable SPL safeguards'

**Comment by cmutt78** [comment]
This is an item related to Splunk Cloud's implementation;  Will add to docs but no fix to make.
