### ISSUE TITLE
SSRG109 - Malicious PowerShell Process - Execution Policy Bypass - Adding filtering

### ISSUE THREAD

**Issue by jward51** [spicosolutions/thepeoplessiem#9]
Added filtering to tune out Splunk_TA_windows, SplunkUniversalForwarder, and Windows Defender logs 

| tstats summariesonly=t  values(Processes.process_id) as process_id, values(Processes.parent_process_id) as parent_process_id values(Processes.process) as process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name=powershell.exe (Processes.process="* -ex*" OR Processes.process="* bypass *") by Processes.process_id, Processes.user, Processes.dest
|rename Processes.* as *
**| search NOT ((process = "*\\Splunk_TA_windows\\*" OR process = "*\\SplunkUniversalForwarder\\*" OR process = "*\\Machine\\Scripts\\Startup\\ipamprovisioning.ps1*" OR process = "*\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\*"))**

**Comment by cmutt78** [comment]
what is ipamprovisioning?

**Comment by jward51** [comment]
Verify that SSRG109 search filters were added
